import "./globals.css";
import "leaflet/dist/leaflet.css";
import type { Metadata } from "next";
import { SoundProvider } from "@/context/SoundContext";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="cs">
      <body>
        <SoundProvider>
          {children}
        </SoundProvider>
      </body>
    </html>
  );
}